import pandas as pd
import os
import glob

# =============================================================================
# OPERATION MODE TRANSLATOR
# =============================================================================
# This script acts as a secondary controller. It reads the optimized power 
# setpoints generated by Pyomo and translates them into actionable "Operation Modes"
# (e.g., Peak Shaving, Arbitrage, Self-Consumption) that physical inverters understand.

def definir_modo_operacao(row, p_grid_max):
    """
    Evaluates the power flows of a single timestep (1 hour) and classifies 
    the system's behavior into a specific operational mode.
    """
    
    # Tolerance for floating-point inaccuracies (e.g., treating 0.00001W as 0W)
    tol = 0.001 
    
    # Extract values from the current row (representing a single hour)
    p_grid_buy = row.get('Rede_Importacao_kW', 0)
    p_grid_sell = row.get('Rede_Exportacao_kW', 0)
    p_ch_ev = row.get('VE_Carga_kW', 0)
    p_dis_ev = row.get('VE_Descarga_kW', 0)
    p_ch_bat = row.get('BESS_Carga_kW', 0)
    p_dis_bat = row.get('BESS_Descarga_kW', 0)
    p_load = row.get('Instalacao_PL_kW', 0)
    
    # Calculate total charging and discharging power of all energy storage elements (BESS + EVs)
    p_ch_total = p_ch_bat + p_ch_ev
    p_dis_total = p_dis_bat + p_dis_ev
    
    # -------------------------------------------------------------------------
    # DECISION TREE FOR OPERATION MODES
    # -------------------------------------------------------------------------
    
    # 1. Peak Shaving (PS)
    # Triggered if batteries/EVs are discharging AND the facility's raw load exceeds the grid limit.
    # The system is discharging specifically to avoid grid penalties.
    if p_dis_total > tol and p_load > p_grid_max:
        return "PS"
        
    # 2. Vehicle-to-Home (V2H) and Self-Consumption (SC - Discharge)
    # Triggered if storage is discharging, but NOT selling to the grid (export is ~0).
    # This means the discharged energy is being consumed locally by the facility.
    elif p_dis_total > tol and p_grid_sell <= tol:
        # If the EV is contributing to the discharge, classify it as V2H
        if p_dis_ev > tol:
            return "V2H"                 
        # Otherwise, only the stationary battery (BESS) is discharging
        else:
            return "SC (Discharge)"
            
    # 3. Arbitrage (Trading energy with the grid for profit)
    # Charge Arbitrage: Storing energy from the grid (buying) to use/sell later.
    elif p_ch_total > tol and p_grid_buy > tol:
        return "ARB (Charge)"
    # Discharge Arbitrage: Selling stored energy back to the grid for profit.
    elif p_dis_total > tol and p_grid_sell > tol:
        return "ARB (Discharge)"
        
    # 4. Self-Consumption (SC - Charge) / Solar Charging
    # Triggered if storage is charging, but NOT buying from the grid (import is ~0).
    # This implies the batteries/EVs are charging exclusively from excess Solar PV.
    elif p_ch_total > tol and p_grid_buy <= tol:
        return "SC (Charge)"
        
    # 5. IDLE
    # If no significant charging or discharging is happening, the system is resting.
    else:
        return "IDLE"

def processar_modos_csv():
    """
    Scans the directory for Pyomo results, aggregates the 3-phase data into 
    global facility metrics, and applies the mode translation logic.
    """
    
    # 1. Look for all result folders generated by the Optimizer
    pastas_resultados = glob.glob('RESULTS_*')
    
    if not pastas_resultados:
        print("No results folders found. Run the Optimizer first.")
        return

    # 2. Read the Maximum Contracted Power from css_power.csv
    try:
        # Reads the grid limit file (assuming it contains limits per phase)
        df_css = pd.read_csv('css_power.csv', header=None)
        # Sums all values to get the GLOBAL contracted limit for the facility
        P_GRID_MAX = df_css.apply(pd.to_numeric, errors='coerce').values.sum()
        print(f"-> P_GRID_MAX successfully read: {P_GRID_MAX} W")
    except FileNotFoundError:
        print("-> File 'css_power.csv' not found. Using default value: 20000 W.")
        P_GRID_MAX = 20000

    # 3. Read the Facility Base Load (PL)
    try:
        # header=None prevents pandas from using the first data row as column names
        df_pl = pd.read_csv('pl.csv', header=None) 
        # Sums the 3 phases (axis=0) to obtain the total facility consumption curve
        total_pl = df_pl.sum(axis=0) 
    except FileNotFoundError:
        print("-> File 'pl.csv' not found. Facility base load will be set to 0.")
        total_pl = pd.Series([0]*24)

    # 4. Iterate through each generated results folder
    for pasta in pastas_resultados:
        print(f"\nProcessing CSVs in folder: {pasta}...")
        
        try:
            # 4.1 Read the new 3-Phase CSVs and aggregate them
            grid_import_df = pd.read_csv(os.path.join(pasta, 'grid_import_per_phase.csv'), index_col=0)
            grid_export_df = pd.read_csv(os.path.join(pasta, 'grid_export_per_phase.csv'), index_col=0)
            
            # Sum phases 1 + 2 + 3 to get the global facility import/export
            total_grid_import = grid_import_df.sum(axis=1) 
            total_grid_export = grid_export_df.sum(axis=1) 

            # 4.2 Read EV and BESS CSVs (these are already generated as global totals)
            pev_charge = pd.read_csv(os.path.join(pasta, 'PEV_h.csv'), index_col=0)
            pev_discharge = pd.read_csv(os.path.join(pasta, 'PEVdc_h.csv'), index_col=0)
            bess_charge = pd.read_csv(os.path.join(pasta, 'PBess_h.csv'), index_col=0)
            bess_discharge = pd.read_csv(os.path.join(pasta, 'PBessdc_h.csv'), index_col=0)
            
            # 5. Build a temporary unified DataFrame crossing all relevant columns
            df = pd.DataFrame({
                'Rede_Importacao_kW': total_grid_import.values,
                'Rede_Exportacao_kW': total_grid_export.values,
                'VE_Carga_kW': pev_charge.iloc[:, 0].values,
                'VE_Descarga_kW': pev_discharge.iloc[:, 0].values,
                'BESS_Carga_kW': bess_charge.iloc[:, 0].values,
                'BESS_Descarga_kW': bess_discharge.iloc[:, 0].values,
                'Instalacao_PL_kW': total_pl.values if isinstance(total_pl, pd.Series) else total_pl
            }, index=range(1, 25))
            
            df.index.name = 'Hora'
            
            # 6. Apply the translation logic to each row (hour) to find the Operation Mode
            df['Modo_Operacao'] = df.apply(lambda row: definir_modo_operacao(row, P_GRID_MAX), axis=1)
            
            # Isolate just the target column
            df_apenas_modos = df[['Modo_Operacao']]
                
            # 7. Save the final results as a new CSV inside the same run folder
            ficheiro_saida = os.path.join(pasta, 'Modos_Operacao_Analisados.csv')
            df_apenas_modos.to_csv(ficheiro_saida) 
                
            print(f"   Translation successfully saved to: {ficheiro_saida}")
            
        except FileNotFoundError as e:
            # Skips the folder if it doesn't contain all required CSVs (e.g., a failed run)
            print(f"   [ERROR] Missing files in folder {pasta}: {e}")
            continue

# =============================================================================
# MAIN EXECUTION
# =============================================================================
if __name__ == "__main__":
    processar_modos_csv()